spring:
  # 데이터베이스 설정: 테스트 실행 시 메모리에만 DB 생성, 테스트 끝나면 데이터 사라짐
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddlAuto: create